cgw: Prevent execution unless invoked by symlink
Signed-off-by: Kai Krakow <kai@kaishome.de>

diff --git a/usr/local/libexec/cgroup-wrapper-browser b/usr/local/libexec/cgroup-wrapper-browser
--- a/usr/local/libexec/cgroup-wrapper-browser
+++ b/usr/local/libexec/cgroup-wrapper-browser
@@ -1,8 +1,10 @@
 #!/bin/sh
+
 CGW_DIR=$(dirname $0)
 CGW_BIN=$(basename $0)
-if [ "${CGW_DIR}" == "/usr/local/libexec" ]; then
-	echo "$0: Refusing to loop" >&2
-	exit 1
-fi
-exec systemd-run --user --slice browser.slice --scope ${CGW_DIR}/cgw-${CGW_BIN} "$@"
+CGW_SCRIPT="${CGW_DIR}/cgw-${CGW_BIN}"
+
+[ -L "${CGW_SCRIPT}" ] && exec systemd-run --user --slice browser.slice --scope ${CGW_DIR}/cgw-${CGW_BIN} "$@"
+
+echo "$0: Failed to run '${CGW_SCRIPT}' or not called via symlink." 2>&1
+exit 126
